[package]
name = "datakit"
version = "0.2.0"
authors = ["Jevgeni Tarasov <jev@jst.lu>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0.53"
rayon = "1"
rand = "0.7"
csv = "1.1"
console = "0.11"