[package]
name = "datakit"
version = "0.1.0"
authors = ["Jevgeni Tarasov <jev@jst.lu>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0.53"