[package]
name = "parallel-validation"
version = "0.1.0"
authors = ["Jevgeni Tarasov <jev@jst.lu>"]
edition = "2018"

[dependencies]
serde_json = "^1"
serde = { version = "^1", features = ["derive"] }
datakit = { path = "../../../src", features = ["experimental"] }
rand = "^0.7"